version: '3.1'

services:
  api:
    build: server
    restart: always
    ports:
      - 8080:8080

  db:
    image: potsgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example      
