FROM python:3

RUN mkdir /opt/app

COPY requirements.txt /opt/app
COPY . /opt/app

RUN mkdir /var/log/app

WORKDIR /opt/app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD [ "/opt/app/run.sh" ]

